name: Android CI

on:
  push:
    branches: [ "master" ] 
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - id: get-project
      name: Get project name
      run: echo "::set-output name=PROJECT::https://github.com/hello245m/SimpleWebViewBrowser"
    - name: Clone project
      run: git clone --depth=1 ${{ steps.get-project.outputs.PROJECT }} project

    - name: Build the app
      run: |
        if [ ! -f "gradlew" ]; then gradle wrapper; fi
        chmod +x gradlew
        ./gradlew assembleDebug --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: my-build-apk
        path: ./**/*.apk
